
[functions.send-hazard-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-hazard-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-hazard-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-hazard-notification/*.html" ]

[functions.notify-nearby-workers]
enabled = true
verify_jwt = false
import_map = "./functions/notify-nearby-workers/deno.json"
entrypoint = "./functions/notify-nearby-workers/index.ts"

[functions.sos_dispatcher]
enabled = true
verify_jwt = true
import_map = "./functions/sos_dispatcher/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sos_dispatcher/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sos_dispatcher/*.html" ]

[functions.analyze-hazard-image]
enabled = true
verify_jwt = true
import_map = "./functions/analyze-hazard-image/deno.json"
entrypoint = "./functions/analyze-hazard-image/index.ts"
