// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaIKcSpngGPhxkzHLAYJp4e__BggV0aEw',
    appId: '1:418212768173:android:81cfb56ac613e9f52e5924',
    messagingSenderId: '418212768173',
    projectId: 'riskradar-467315',
    storageBucket: 'riskradar-467315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsffCeKDhOvgPsNwOcP9hmQusqG1AvBo',
    appId: '1:418212768173:ios:9705e23ba4abaf2b2e5924',
    messagingSenderId: '418212768173',
    projectId: 'riskradar-467315',
    storageBucket: 'riskradar-467315.firebasestorage.app',
    androidClientId:
        '418212768173-8ecla7efev8tjaq5c84aitomu2l72hqn.apps.googleusercontent.com',
    iosClientId:
        '418212768173-jp2orta7gsf0bgeqbocpkg3td0slntql.apps.googleusercontent.com',
    iosBundleId: 'com.example.riskradar',
  );
}
